accountapp/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from accountapp.views import SignupView, SigninView

app_name = 'accountapp'

urlpatterns = [
    path('signup/', SignupView.as_view(), name='signup'),
    path('signin/', SigninView.as_view(), name='signin'),
    path('signout/', LogoutView.as_view(), name='signout'),
]

interviewapp/urls.py
from django.urls import path

from interviewapp import views

app_name = 'interviewapp'

urlpatterns = [
    path('', views.QuestionView, name='question'),
    path('result/', views.ResultView, name='result'),
]

sogonggi/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from homeapp import views as homeviews
from homeapp.views import CorpView
from interviewapp import views as interviewviews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homeviews.MainView, name='home'),
    path('thres/', interviewviews.ThresView, name='thres'),
    path('corps/', CorpView.as_view(), name='corp'),
    path('depts/', homeviews.DeptView, name='dept'),
    path('accounts/', include('accountapp.urls')),
    path('interviews/', include('interviewapp.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

homeapp/models.py
from django.db import models

# Create your models here.
class Corporation(models.Model):
    corp_id = models.IntegerField(null=False, primary_key=True)
    name = models.TextField(null=False, unique=True)
    summary = models.TextField(null=True)

    def __str__(self):
        return self.name

class Department(models.Model):
    dept_id = models.IntegerField(null=False)
    name = models.TextField(null=False)
    corp_name = models.ForeignKey(Corporation, to_field='name', on_delete=models.CASCADE, related_name='corp', db_column='corp_name')

    def __str__(self):
        return self.name

homeapp/views.py
from django.core.serializers import json
from django.shortcuts import render

from django.views.generic import ListView
from homeapp.models import Corporation, Department


# Create your views here.
def MainView(request):
    if request.method == 'GET':
        return render(request, 'homeapp/home.html')


class CorpView(ListView):
    model = Corporation
    context_object_name = 'corp_list'
    template_name = 'homeapp/corporation.html'


def DeptView(request):
    corp_name = request.GET.get('corp', None)
    dept_list = Department.objects.filter(corp_name=corp_name)
    context = {'dept_list': dept_list}
    return render(request, 'homeapp/department.html', context)

homeapp/templates/homeapp/corporation.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

{% include 'header.html' %}

<div style="margin-top: 10rem; text-align: center;">
    {% for corp in corp_list %}
        <div class="list mx-5">
            <div class="mt-5">
                <h3>{{ corp.name }}</h3>
            </div>
            <div class="summary-box my-5">
                <h5 class="mb-3">선택 가능 직무</h5>
                <p>{{ corp.summary|linebreaksbr }}</p>
            </div>
            <div class="button-box mb-5">
                <a class="start-btn btn rounded-pill" href="{% url 'dept' %}?corp={{ corp.name }}">회사 선택</a>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock %}

homeapp/templates/homeapp/department.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

{% include 'header.html' %}

<div style="margin-top: 10rem; text-align: center;">
    {% for dept in dept_list %}
        <div class="list mx-5">
            <div class="mt-5">
                <h4>{{ dept.name }}</h4>
            </div>
            <div class="button-box mt-4 mb-5">
                <a class="start-btn btn rounded-pill" href="{% url 'interviewapp:question' %}?corp={{ dept.corp_name }}&dept={{ dept.name }}&question=1">직무 선택</a>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock %}

homeapp/templates/homeapp/home.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<style>
    a.menu {
        text-decoration: none;
        color: #505050;
        font-size: 1.6rem;
    }
    a.menu:hover {
        color: white;
    }
    .menu-box {
        display: inline-block;
        margin-top: 5rem;
        text-align: center;
        width: 350px;
        border-radius: 0.9rem;
        background-color: rgba(255, 255, 255, 0.3);
    }
    body {
        text-align: center;
    }
</style>

{% include 'header.html' %}

<nav class="header-btn mt-5 mx-5" style="float: right;">
    {% if not user.is_authenticated %}
        <span class="mx-2"><a href="{% url 'accountapp:signin' %}" class="menu">로그인</a></span>
        <span class="mx-2"><a href="{% url 'accountapp:signup' %}" class="menu">회원가입</a></span>
    {% else %}
        <span class="mx-2">내 페이지</span>
        <span class="mx-2"><a href="{% url 'accountapp:signout' %}" class="menu">로그아웃</a></span>
    {% endif %}
</nav>
<div style="clear: both;"></div>
{% if not user.is_authenticated %}
    <div class="menu-box">
        <img class="mt-5" src="/static/img/document.png" style="width: 12rem;">
        <div class="mt-4 mb-5">
            <a class="start-btn btn rounded-pill disabled mt-1" href="{% url 'corp' %}" style="background-color: #A4A4A4;">면접 시작</a>
            <p class="mt-4">로그인 시 면접을 시작할 수 있습니다</p>
        </div>
    </div>
{% else %}
    <div class="menu-box">
        <img class="mt-5" src="/static/img/document.png" style="width: 12rem;">
        <div class="my-5">
            <a class="start-btn btn rounded-pill" href="{% url 'thres' %}">면접 시작</a>
        </div>
    </div>
{% endif %}
{% endblock %}